"use strict";
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),esc=(s="")=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const state={tasks:[],teams:[],card:{},active:null};
const rules=[
 {label:"Контекст и потребность",points:20,fields:["context","need"]},{label:"Данные и материалы",points:20,fields:["data"]},
 {label:"Ожидаемый результат",points:15,fields:["expected_result"]},{label:"Критерии успеха",points:15,fields:["success_criteria"]},
 {label:"Ограничения",points:10,fields:["constraints"]},{label:"Пользователи",points:10,fields:["users"]},{label:"Связь с бизнесом",points:10,fields:["contact"]}
];
async function api(path,options={}){const r=await fetch("/api"+path,{headers:{"Content-Type":"application/json"},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Ошибка запроса");return d}
function readiness(score){return score>=90?{key:"priority",name:"Приоритетная"}:score>=70?{key:"ready",name:"Готовая"}:score>=40?{key:"workable",name:"Рабочая"}:{key:"draft",name:"Черновик"}}
function plural(n){return n%10===1&&n%100!==11?"задача":n%10>1&&n%10<5&&(n%100<10||n%100>=20)?"задачи":"задач"}
function formCard(){return Object.fromEntries(new FormData($("#taskForm")).entries())}
function rating(card){let score=0;const rows=rules.map(r=>{const yes=r.fields.every(f=>(card[f]||"").trim().length>=3);if(yes)score+=r.points;return{...r,yes}});return{score,rows}}
function scoreUI(card={}){const {score,rows}=rating(card),level=readiness(score);$("#ring").style.setProperty("--value",score);$("#score").textContent=score;$("#level").textContent=level.name;$("#filled").textContent=`${rows.filter(r=>r.yes).length} из 7`;$(".level>i").style.background={draft:"var(--orange)",workable:"var(--purple)",ready:"var(--cyan)",priority:"var(--lime)"}[level.key];$("#breakdown").innerHTML=rows.map(r=>`<div class="break ${r.yes?"yes":""}"><span>${r.label}</span><b>${r.yes?"+"+r.points:"0"}/${r.points}</b><span class="track"><i></i></span></div>`).join("");const next=rows.find(r=>!r.yes);$("#tip").innerHTML=next?`<b>Можно добавить +${next.points}</b>Заполните: ${next.label.toLowerCase()}.`:`<b>Карточка заполнена</b>Все критерии рейтинга подтверждены.`}
function go(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===name));history.replaceState(null,'','#'+name);if(name==='catalog')renderCatalog();if(name==='decisions')renderDecisions();scrollTo({top:0,behavior:'smooth'})}
function toast(title,text){$("#toastTitle").textContent=title;$("#toastText").textContent=text;$("#toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("#toast").classList.remove("show"),3500)}
function loading(btn,on,label){btn.dataset.label??=btn.childNodes[0].textContent;btn.disabled=on;btn.childNodes[0].textContent=on?label:btn.dataset.label}
function fill(card){[...$("#taskForm").elements].forEach(e=>{if(e.name&&Object.hasOwn(card,e.name))e.value=card[e.name]||""});scoreUI(formCard())}
function steps(n){$$('.steps span').forEach((s,i)=>s.classList.toggle('on',i<=n))}

async function analyze(){const text=$("#draft").value.trim(),err=$("#draftError"),btn=$("#analyzeBtn");err.textContent="";if(text.length<12){err.textContent="Добавьте хотя бы одно предложение о задаче.";return}loading(btn,true,"Анализируем… ");try{const d=await api('/analyze',{method:'POST',body:JSON.stringify({description:text})});state.card=d.card;$("#questions").innerHTML=d.questions.map((q,i)=>`<div class="question"><b>${i+1}</b><label>${esc(q.text)}<input data-field="${q.field}" placeholder="${esc(q.placeholder)}"></label></div>`).join('');fill(d.card);$("#questionsPanel").hidden=false;steps(1);$("#questionsPanel").scrollIntoView({behavior:'smooth'})}catch(e){err.textContent=e.message}finally{loading(btn,false)}}
function buildCard(){const card={...state.card};$$('[data-field]').forEach(i=>{if(i.value.trim())card[i.dataset.field]=i.value.trim()});fill(card);$("#cardPanel").hidden=false;steps(2);$("#cardPanel").scrollIntoView({behavior:'smooth'})}
function resetBuilder(){$("#draft").value="";$("#counter").textContent="0 / 1200";$("#questionsPanel").hidden=true;$("#cardPanel").hidden=true;$("#taskForm").reset();steps(0);scoreUI({})}
async function publish(e){e.preventDefault();const card=formCard(),err=$("#publishError"),btn=e.submitter;err.textContent="";if(!card.title.trim()||!card.context.trim()||!card.need.trim()){err.textContent="Нужны название, контекст и потребность.";return}if(!$("#confirm").checked){err.textContent="Подтвердите достоверность данных.";return}loading(btn,true,"Публикуем… ");try{const task=await api('/tasks',{method:'POST',body:JSON.stringify({...card,confirmed:true})});state.tasks.unshift(task);counts();resetBuilder();go('catalog');toast('Задача опубликована',`Рейтинг ${task.score}/100. Команды уже могут откликнуться.`)}catch(x){err.textContent=x.message}finally{loading(btn,false)}}

function date(s){return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(s))}
function renderCatalog(){let q=$("#search").value.trim().toLowerCase(),ind=$("#industry").value,lvl=$("#readiness").value,sort=$("#sort").value;let tasks=state.tasks.filter(t=>(!q||`${t.title} ${t.context} ${t.need}`.toLowerCase().includes(q))&&(!ind||t.industry===ind)&&(!lvl||readiness(t.score).key===lvl));tasks.sort((a,b)=>sort==='newest'?new Date(b.created_at)-new Date(a.created_at):sort==='proposals'?b.proposals.length-a.proposals.length:b.score-a.score);$("#resultCount").textContent=`${tasks.length} ${plural(tasks.length)}`;$("#empty").hidden=!!tasks.length;$("#cards").innerHTML=tasks.map(t=>{const l=readiness(t.score);return `<article class="card ${l.key}"><div class="card-top"><span class="tag">${esc(t.industry)}</span><span class="status ${l.key}"><i></i>${l.name}</span></div><h2>${esc(t.title)}</h2><p>${esc(t.need||t.context)}</p><div class="metrics"><span class="metric"><small>Отклики</small><b>${t.proposals.length}</b></span><span class="metric"><small>Создана</small><b>${date(t.created_at)}</b></span><span class="card-score">${t.score}<small>/100</small></span></div><button class="open" data-open="${t.id}">Посмотреть задачу <b>→</b></button></article>`}).join('')}
function openTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;state.active=id;const details=[["Контекст",t.context],["Потребность",t.need],["Пользователи",t.users],["Данные",t.data],["Ожидаемый результат",t.expected_result],["Критерии успеха",t.success_criteria],["Ограничения",t.constraints],["Связь",t.contact]];$("#dialogBody").innerHTML=`<div class="dialog-inner"><span class="tag">${esc(t.industry)}</span><h2>${esc(t.title)}</h2><div class="dialog-score">${t.score}/100</div><div class="details">${details.map(d=>`<div class="detail"><small>${d[0]}</small><p>${esc(d[1]||'Не указано')}</p></div>`).join('')}</div><form class="proposal-form" id="proposalForm"><h3>Предложить решение</h3><p>Опишите подход. Решение бизнес примет вручную.</p><div class="form-grid"><label class="field">Команда<select name="team_id">${state.teams.map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.skills.slice(0,2).join(', '))}</option>`).join('')}</select></label><label class="field">Срок<input name="timeline" placeholder="Например, 3 недели"></label><label class="field wide">Идея решения<textarea name="idea" rows="3"></textarea></label><label class="field wide">План работы<textarea name="plan" rows="3"></textarea></label><label class="field wide">Ссылка на прототип<input name="prototype" type="url" placeholder="https://..."></label></div><p class="error"></p><button class="primary" type="submit">Отправить отклик →</button></form></div>`;$("#proposalForm").addEventListener('submit',submitProposal);$("#taskDialog").showModal()}
async function submitProposal(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries()),err=e.currentTarget.querySelector('.error'),btn=e.submitter;err.textContent="";if(!data.idea.trim()||!data.plan.trim()||!data.timeline.trim()){err.textContent="Заполните идею, план и срок.";return}loading(btn,true,"Отправляем… ");try{const p=await api(`/tasks/${state.active}/proposals`,{method:'POST',body:JSON.stringify(data)});state.tasks.find(t=>t.id===state.active).proposals.push(p);counts();$("#taskDialog").close();renderCatalog();toast('Отклик отправлен','Он появился в кабинете бизнеса.')}catch(x){err.textContent=x.message}finally{loading(btn,false)}}
function renderDecisions(){const tasks=state.tasks.filter(t=>t.proposals.length);$("#decisionList").innerHTML=tasks.length?tasks.map(t=>`<article class="decision"><header><div><p>${esc(t.industry)} · ${t.proposals.length} откл.</p><h2>${esc(t.title)}</h2></div><b>${t.score}/100</b></header>${t.proposals.map(p=>`<div class="proposal"><div class="team"><span class="avatar">${esc(p.team_name.split(/\s+/).map(w=>w[0]).join('').slice(0,2))}</span>${esc(p.team_name)}</div><p><b>${esc(p.idea)}</b>${esc(p.plan)} · ${esc(p.timeline)}</p><div class="decision-buttons"><button class="accept ${p.status==='selected'?'selected':''}" data-choice="selected" data-proposal="${p.id}" ${p.status!=='pending'?'disabled':''}>${p.status==='selected'?'Выбрана':'Выбрать'}</button><button class="reject ${p.status==='rejected'?'selected':''}" data-choice="rejected" data-proposal="${p.id}" ${p.status!=='pending'?'disabled':''}>${p.status==='rejected'?'Отклонена':'Отклонить'}</button></div></div>`).join('')}</article>`).join(''):`<div class="empty"><h2>Откликов пока нет</h2><p>Когда команда предложит решение, оно появится здесь.</p></div>`}
async function decide(id,choice){try{const up=await api(`/proposals/${id}/decision`,{method:'POST',body:JSON.stringify({decision:choice})});state.tasks.forEach(t=>{const p=t.proposals.find(x=>x.id===id);if(p)Object.assign(p,up)});counts();renderDecisions();toast(choice==='selected'?'Команда выбрана':'Отклик отклонён','Решение бизнеса сохранено.')}catch(e){toast('Ошибка',e.message)}}
function counts(){$("#taskCount").textContent=state.tasks.length;$("#proposalCount").textContent=state.tasks.flatMap(t=>t.proposals).filter(p=>p.status==='pending').length;const cur=$("#industry").value,inds=[...new Set(state.tasks.map(t=>t.industry))].sort();$("#industry").innerHTML='<option value="">Все темы</option>'+inds.map(x=>`<option>${esc(x)}</option>`).join('');$("#industry").value=cur}
async function load(){try{const d=await api('/bootstrap');state.tasks=d.tasks;state.teams=d.teams;counts();renderCatalog();renderDecisions()}catch(e){toast('Сервер недоступен','Запустите проект командой python app.py.')}}

$$('.nav').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$$('[data-new]').forEach(b=>b.addEventListener('click',()=>go('builder')));$("#draft").addEventListener('input',e=>$("#counter").textContent=`${e.target.value.length} / 1200`);$("#exampleBtn").addEventListener('click',()=>{$("#draft").value='Хотим сократить очереди в столовой университета с помощью цифрового сервиса.';$("#draft").dispatchEvent(new Event('input'))});$("#analyzeBtn").addEventListener('click',analyze);$("#buildBtn").addEventListener('click',buildCard);$("#taskForm").addEventListener('input',()=>scoreUI(formCard()));$("#taskForm").addEventListener('submit',publish);['#search','#industry','#readiness','#sort'].forEach(s=>$(s).addEventListener('input',renderCatalog));$("#cards").addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openTask(b.dataset.open)});$("#decisionList").addEventListener('click',e=>{const b=e.target.closest('[data-choice]');if(b)decide(b.dataset.proposal,b.dataset.choice)});$(".close").addEventListener('click',()=>$("#taskDialog").close());$("#taskDialog").addEventListener('click',e=>{if(e.target===$("#taskDialog"))e.target.close()});scoreUI({});load();go(['builder','catalog','decisions'].includes(location.hash.slice(1))?location.hash.slice(1):'builder');
