"use strict";
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),esc=(s="")=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const state={tasks:[],teams:[],card:{},active:null,knownUpdates:new Set(),user:null,pendingAuth:null};
const rules=[
 {label:"Контекст и потребность",points:20,fields:["context","need"]},{label:"Данные и материалы",points:20,fields:["data"]},
 {label:"Ожидаемый результат",points:15,fields:["expected_result"]},{label:"Критерии успеха",points:15,fields:["success_criteria"]},
 {label:"Ограничения",points:10,fields:["constraints"]},{label:"Пользователи",points:10,fields:["users"]},{label:"Связь с бизнесом",points:10,fields:["contact"]}
];
const localStorageKey="taskforge.demo.v1";
const localTeams=[
 {id:"team-1",name:"Data Nomads",interests:["ритейл","аналитика"],skills:["Python","ML","FastAPI"]},
 {id:"team-2",name:"Qadam Lab",interests:["образование","доступность"],skills:["UX","JavaScript","NLP"]},
 {id:"team-3",name:"Green Pulse",interests:["экология","города"],skills:["IoT","DataViz","Python"]},
 {id:"team-4",name:"Finity",interests:["финтех","безопасность"],skills:["React","Risk","API"]},
 {id:"team-5",name:"Steppe Vision",interests:["CV","логистика"],skills:["Computer Vision","Python","Mobile"]}
];
const localQuestions={
 need:["Что именно должно измениться после решения задачи?","Сформулируйте желаемое изменение"],users:["Кто будет пользоваться результатом?","Роли или группы пользователей"],
 data:["Какие данные, материалы или примеры вы предоставите?","Формат, объём и источник данных"],expected_result:["Какой конкретный результат должна передать команда?","Прототип, модель, исследование или сервис"],
 success_criteria:["По каким измеримым признакам вы примете решение?","Метрики или проверяемые условия"],constraints:["Какие есть сроки, технологии или ограничения?","Срок, стек, запреты"],
 contact:["Как команда сможет общаться с бизнесом?","Контакт и формат консультаций"]
};
const clone=value=>typeof structuredClone==="function"?structuredClone(value):JSON.parse(JSON.stringify(value));
const localId=prefix=>`${prefix}-${typeof crypto!=="undefined"&&crypto.randomUUID?crypto.randomUUID().slice(0,8):Math.random().toString(16).slice(2,10)}`;
const authStorageKey="taskforge.auth.v1",demoCode="1234";
function loadSession(){try{const user=JSON.parse(localStorage.getItem(authStorageKey));return user&&["student","business"].includes(user.role)?user:null}catch(_){return null}}
function saveSession(user){try{localStorage.setItem(authStorageKey,JSON.stringify(user))}catch(_){}}
function displayName(user=state.user){return user?`${user.first_name} ${user.last_name}`.trim():""}
function participantName(user=state.user){return user?.participant_type==="team"&&user.team_name?user.team_name:displayName(user)}
function isBusiness(){return state.user?.role==="business"}
function isStudent(){return state.user?.role==="student"}
function canManageTask(task){return isBusiness()&&(!task.owner_id||task.owner_id===state.user.id)}
function ensureRole(role){if(!state.user){openAuth(role);return false}if(state.user.role!==role){toast("Недоступно",role==="business"?"Это действие доступно только бизнесу.":"Отклики могут отправлять только студенты и команды.");return false}return true}
function syncAuthFields(){const role=new FormData($("#authForm")).get("role"),type=$("#authForm [name=participant_type]").value;$("#participationField").hidden=role!=="student";$("#teamNameField").hidden=role!=="student"||type!=="team"}
function openAuth(role){$("#authError").textContent="";$("#codeError").textContent="";$("#authForm").hidden=false;$("#codeForm").hidden=true;if(role){const input=$(`#authForm [name=role][value="${role}"]`);if(input)input.checked=true}syncAuthFields();if(!$("#authDialog").open)$("#authDialog").showModal()}
function updateAuthUI(){const user=state.user,business=isBusiness();$("#authButton").hidden=!!user;$("#userMenu").hidden=!user;if(user){$("#userName").textContent=displayName(user);$("#userRole").textContent=business?"Бизнес":user.participant_type==="team"?"Студенческая команда":"Студент";$("#userAvatar").textContent=`${user.first_name?.[0]||""}${user.last_name?.[0]||""}`.toUpperCase()}document.body.dataset.role=user?.role||"guest";const builderNav=$('[data-view="builder"]'),decisionsNav=$('[data-view="decisions"]');builderNav.hidden=!!user&&!business;decisionsNav.hidden=!business;$$('[data-new]').forEach(button=>button.hidden=!business)}
function requestCode(event){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries()),error=$("#authError"),digits=String(data.phone||"").replace(/\D/g,"");error.textContent="";if(!String(data.first_name||"").trim()||!String(data.last_name||"").trim()){error.textContent="Укажите имя и фамилию.";return}if(digits.length<10||digits.length>15){error.textContent="Укажите корректный номер телефона.";return}if(data.role==="student"&&data.participant_type==="team"&&!String(data.team_name||"").trim()){error.textContent="Укажите название команды.";return}state.pendingAuth={id:`user-${digits.slice(-10)}`,role:data.role,first_name:String(data.first_name).trim(),last_name:String(data.last_name).trim(),phone:String(data.phone).trim(),participant_type:data.role==="student"?data.participant_type:"business",team_name:data.role==="student"&&data.participant_type==="team"?String(data.team_name).trim():"",verified:true};$("#codePhone").textContent=state.pendingAuth.phone;$("#demoCode").textContent=demoCode;$("#authForm").hidden=true;$("#codeForm").hidden=false;$("#codeForm [name=code]").focus()}
function verifyCode(event){event.preventDefault();const code=String(new FormData(event.currentTarget).get("code")||"").trim(),error=$("#codeError");error.textContent="";if(code!==demoCode){error.textContent="Неверный код. В демо-режиме используйте 1234.";return}state.user={...state.pendingAuth,authenticated_at:new Date().toISOString()};state.pendingAuth=null;saveSession(state.user);event.currentTarget.reset();$("#authDialog").close();updateAuthUI();if(isBusiness())go("builder");else showStudentCatalog();toast("Вход выполнен",`${displayName()} · ${isBusiness()?"Бизнес":participantName()}`)}
function logout(){try{localStorage.removeItem(authStorageKey)}catch(_){}state.user=null;state.pendingAuth=null;if($("#taskDialog").open)$("#taskDialog").close();updateAuthUI();go("catalog");openAuth()}
function enrichLocal(task){let score=0;const breakdown=[],missing=[];for(const rule of rules){const earned=task.confirmed&&rule.fields.every(field=>String(task[field]||"").trim().length>=3)?rule.points:0;score+=earned;breakdown.push({label:rule.label,earned,max:rule.points});if(!earned)missing.push(rule.label)}return Object.assign(task,{score,breakdown,missing,readiness:score>=90?"priority":score>=70?"ready":score>=40?"workable":"draft"})}
function seedTask(data){return enrichLocal(Object.assign({users:"",data:"",constraints:"",expected_result:"",success_criteria:"",contact:"",confirmed:true,published:true,stage:"open",deadline:"",updates:[],proposals:[]},data))}
function seedLocalDb(){
 const tasks=[
  seedTask({id:"task-1",title:"Сократить очереди в университетской столовой",industry:"Образование",context:"В обед студенты ждут заказ до 25 минут, сотрудники не видят будущую нагрузку.",need:"Нужен сервис предзаказа и прогнозирования нагрузки по времени.",created_at:"2026-09-22T09:00:00+00:00",users:"Студенты, преподаватели и сотрудники столовой.",data:"История продаж за 6 месяцев, меню и расписание пар.",constraints:"MVP без онлайн-оплаты; запуск за 4 недели.",expected_result:"Веб-MVP предзаказа и панель прогноза нагрузки.",success_criteria:"Среднее ожидание ниже 10 минут; 60% заказов вовремя.",contact:"Менеджер столовой; консультация по средам."}),
  seedTask({id:"task-2",title:"Прогнозировать остатки скоропортящихся товаров",industry:"Ритейл",context:"Магазины списывают свежие продукты из-за неточного ручного заказа.",need:"Нужен прогноз спроса на 7 дней по товарным категориям.",created_at:"2026-09-21T13:30:00+00:00",users:"Управляющие магазинов и специалисты по закупкам.",data:"Продажи, остатки, промо и списания по 12 магазинам за год.",constraints:"Без персональных данных; запуск на обычном ноутбуке.",expected_result:"Модель прогноза и рекомендации объёма заказа.",success_criteria:"Ошибка ниже baseline минимум на 15%.",contact:"Продуктовый аналитик; две консультации в неделю."}),
  seedTask({id:"task-3",title:"Карта переполненных контейнерных площадок",industry:"Экология",context:"Жители сообщают о переполнении по разным каналам, заявки дублируются.",need:"Нужно собирать сигналы на карте и расставлять приоритеты.",created_at:"2026-09-20T08:15:00+00:00",users:"Жители и диспетчеры службы вывоза.",data:"Примеры обращений и координаты 80 площадок.",expected_result:"Прототип карты с фильтром по срочности.",success_criteria:"Критичные точки находятся меньше чем за 2 минуты.",contact:"Координатор проекта, созвон раз в неделю."}),
  seedTask({id:"task-4",title:"Объяснять причины отклонения заявок на микрокредит",industry:"Финтех",context:"Клиенты получают формальный отказ и повторяют заявку без изменений.",need:"Нужно понятное объяснение без раскрытия закрытых правил скоринга.",created_at:"2026-09-19T15:45:00+00:00",users:"Клиенты приложения и специалисты поддержки.",expected_result:"Прототип экрана и библиотека безопасных формулировок.",constraints:"Без чувствительных признаков и раскрытия весов скоринга."}),
  seedTask({id:"task-5",title:"Навигация по доступным маршрутам внутри кампуса",industry:"Городская среда",context:"Гостям сложно понять, какой вход доступен маломобильному человеку.",need:"Нужна карта доступных входов и маршрутов.",created_at:"2026-09-18T11:20:00+00:00",users:"Маломобильные посетители и сопровождающие."})
 ];
 tasks[0].proposals.push({id:"proposal-1",team_id:"team-2",team_name:"Qadam Lab",idea:"PWA-предзаказ с временными слотами",plan:"Прототип, тест на одной точке, анализ очереди",timeline:"3 недели",prototype:"https://example.com/demo",status:"pending",created_at:new Date().toISOString()});
 tasks[1].proposals.push({id:"proposal-2",team_id:"team-1",team_name:"Data Nomads",idea:"Иерархический прогноз по магазинам",plan:"Очистка, backtest, API прогноза",timeline:"4 недели",prototype:"https://example.com/demo",status:"pending",created_at:new Date().toISOString()});
 return {tasks,teams:clone(localTeams)};
}
let localDbCache;
function loadLocalDb(){if(localDbCache)return localDbCache;try{const saved=JSON.parse(localStorage.getItem(localStorageKey));if(saved&&Array.isArray(saved.tasks)&&Array.isArray(saved.teams)){saved.tasks.forEach(task=>Object.assign(task,{stage:task.stage||"open",deadline:task.deadline||"",updates:Array.isArray(task.updates)?task.updates:[]}));return localDbCache=saved}}catch(_){}return localDbCache=seedLocalDb()}
function saveLocalDb(db){localDbCache=db;try{localStorage.setItem(localStorageKey,JSON.stringify(db))}catch(_){}}
function analyzeLocal(text){const clean=text.replace(/\s+/g," ").trim(),low=clean.toLowerCase(),words=clean.split(" ");let industry="Другое";const industries={"Образование":["университет","школ","студент","обуч"],"Ритейл":["магазин","товар","продаж"],"Финтех":["банк","кредит","финанс"],"Экология":["отход","мусор","эколог"],"Городская среда":["город","маршрут","транспорт","кампус"]};for(const [name,marks] of Object.entries(industries))if(marks.some(mark=>low.includes(mark))){industry=name;break}const title=words.slice(0,9).join(" ").replace(/[.,;:!?]+$/g,"")+(words.length>9?"…":""),card={title:title.slice(0,100),industry,context:clean,need:"",users:"",data:"",constraints:"",expected_result:"",success_criteria:"",contact:""};const markers={users:["для ","пользовател","клиент","сотрудник","студент"],data:["данн","csv","таблиц","api"],constraints:["срок","нельзя","огранич","недел"],expected_result:["прототип","сервис","модель","приложение"],success_criteria:["процент","%","метрик","сниз"],contact:["контакт","созвон","консультац"]};const order=["need","users","data","expected_result","success_criteria","constraints","contact"],found=new Set(Object.entries(markers).filter(([,marks])=>marks.some(mark=>low.includes(mark))).map(([field])=>field)),missing=order.filter(field=>!found.has(field));if(missing.length<3)missing.push(...order.filter(field=>!missing.includes(field)));return {card,questions:missing.slice(0,5).map(field=>({field,text:localQuestions[field][0],placeholder:localQuestions[field][1]})),analysis:{mode:"browser-local",invented_facts:false}}}
function localApi(path,options={}){
 const db=loadLocalDb();let input={};
 if(options.body)try{input=JSON.parse(options.body)}catch(_){throw Error("Некорректный JSON")}
 if(path==="/bootstrap")return clone({tasks:[...db.tasks].sort((a,b)=>b.score-a.score),teams:db.teams});
 if(path==="/tasks"&&(!options.method||options.method==="GET"))return clone(db.tasks);
 if(path==="/analyze"){const text=String(input.description||"").trim();if(text.length<12)throw Error("Описание должно содержать хотя бы 12 символов");return analyzeLocal(text.slice(0,1200))}
 if(path==="/tasks"&&options.method==="POST"){
  if(!["title","context","need"].every(field=>String(input[field]||"").trim()))throw Error("Нужны название, контекст и потребность");
  if(input.confirmed!==true)throw Error("Подтвердите карточку");
  if(input.deadline&&!/^\d{4}-\d{2}-\d{2}$/.test(input.deadline))throw Error("Укажите дату окончания приёма откликов");
  if(input.deadline&&input.deadline<localDateString())throw Error("Дата окончания приёма откликов не может быть в прошлом.");
  const fields=["title","industry","context","need","users","data","constraints","expected_result","success_criteria","contact","deadline"],task=Object.fromEntries(fields.map(field=>[field,String(input[field]||"").trim().slice(0,2000)]));
  Object.assign(task,{id:localId("task"),title:task.title.slice(0,100),industry:task.industry||"Другое",confirmed:true,published:true,created_at:new Date().toISOString(),stage:"open",deadline:task.deadline||"",owner_id:String(input.owner_id||""),owner_name:String(input.owner_name||""),updates:[],proposals:[]});
  enrichLocal(task);db.tasks.push(task);saveLocalDb(db);return clone(task)
 }
 let match=path.match(/^\/tasks\/([^/]+)\/stage$/);
 if(match){const task=db.tasks.find(item=>item.id===match[1]),stage=input.stage;if(!task)throw Error("Задача не найдена");if(!["open","in_progress","completed"].includes(stage))throw Error("Выберите один из этапов задачи");const previous=task.stage||"open";if(previous!==stage){const changedAt=new Date().toISOString();task.updates??=[];task.updates.push({id:localId("update"),type:"stage",from:previous,to:stage,created_at:changedAt});task.stage=stage;task.stage_changed_at=changedAt}saveLocalDb(db);return clone(task)}
 match=path.match(/^\/tasks\/([^/]+)\/proposals$/);
 if(match){
  const task=db.tasks.find(item=>item.id===match[1]),legacyTeam=db.teams.find(item=>item.id===input.team_id),applicantId=String(input.applicant_id||input.team_id||""),applicantName=String(input.applicant_name||input.team_name||legacyTeam?.name||"").trim(),participantType=input.participant_type==="student"?"student":"team";
  if(!task||!applicantId||!applicantName)throw Error("Задача или участник не найдены");
  if((task.stage||"open")!=="open")throw Error("Приём откликов закрыт: задача уже в работе или завершена");
  if(task.deadline&&task.deadline<localDateString())throw Error("Срок приёма откликов истёк");
  if(!["idea","plan","timeline"].every(field=>String(input[field]||"").trim()))throw Error("Заполните идею, план и срок");
  const proposal={id:localId("proposal"),team_id:applicantId,team_name:applicantName,participant_type:participantType,idea:String(input.idea).slice(0,500),plan:String(input.plan).slice(0,1000),timeline:String(input.timeline).slice(0,100),prototype:String(input.prototype||"").slice(0,500),status:"pending",created_at:new Date().toISOString()};
  task.proposals.push(proposal);saveLocalDb(db);return clone(proposal)
 }
 match=path.match(/^\/proposals\/([^/]+)\/decision$/);
 if(match){if(!["selected","rejected"].includes(input.decision))throw Error("Можно выбрать или отклонить");for(const task of db.tasks){const proposal=task.proposals.find(item=>item.id===match[1]);if(proposal){proposal.status=input.decision;proposal.decided_at=new Date().toISOString();saveLocalDb(db);return clone(proposal)}}throw Error("Отклик не найден")}
 throw Error("Маршрут не найден")
}
let apiMode="remote";
async function api(path,options={}){if(apiMode==="local")return localApi(path,options);let response;try{response=await fetch("/api"+path,{headers:{"Content-Type":"application/json"},...options})}catch(_){apiMode="local";return localApi(path,options)}const type=response.headers.get("Content-Type")||"";if(!type.includes("application/json")){if(response.ok||[404,405,501].includes(response.status)){apiMode="local";return localApi(path,options)}throw Error(`Ошибка запроса (HTTP ${response.status})`)}const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||`Ошибка запроса (HTTP ${response.status})`);return data}
function readiness(score){return score>=90?{key:"priority",name:"Приоритетная"}:score>=70?{key:"ready",name:"Готовая"}:score>=40?{key:"workable",name:"Рабочая"}:{key:"draft",name:"Черновик"}}
function plural(n){return n%10===1&&n%100!==11?"задача":n%10>1&&n%10<5&&(n%100<10||n%100>=20)?"задачи":"задач"}
function formCard(){return Object.fromEntries(new FormData($("#taskForm")).entries())}
function rating(card){let score=0;const rows=rules.map(r=>{const yes=r.fields.every(f=>(card[f]||"").trim().length>=3);if(yes)score+=r.points;return{...r,yes}});return{score,rows}}
function scoreUI(card={}){const {score,rows}=rating(card),level=readiness(score);$("#ring").style.setProperty("--value",score);$("#score").textContent=score;$("#level").textContent=level.name;$("#filled").textContent=`${rows.filter(r=>r.yes).length} из 7`;$(".level>i").style.background={draft:"var(--orange)",workable:"var(--purple)",ready:"var(--pink-soft)",priority:"var(--pink)"}[level.key];$("#breakdown").innerHTML=rows.map(r=>`<div class="break ${r.yes?"yes":""}"><span>${r.label}</span><b>${r.yes?"+"+r.points:"0"}/${r.points}</b><span class="track"><i></i></span></div>`).join("");const next=rows.find(r=>!r.yes);$("#tip").innerHTML=next?`<b>Можно добавить +${next.points}</b>Заполните: ${next.label.toLowerCase()}.`:`<b>Карточка заполнена</b>Все критерии рейтинга подтверждены.`}
function go(name){if(name==="builder"&&!isBusiness()){if(!state.user)openAuth("business");else toast("Раздел для бизнеса","Студенты могут просматривать задачи и отправлять отклики.");name="catalog"}if(name==="decisions"&&!isBusiness()){if(!state.user)openAuth("business");name="catalog"}$$('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===name));history.replaceState(null,'','#'+name);if(name==='catalog')renderCatalog();if(name==='decisions')renderDecisions();if(name==='updates')renderUpdates();scrollTo({top:0,behavior:'smooth'})}
function toast(title,text){$("#toastTitle").textContent=title;$("#toastText").textContent=text;$("#toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("#toast").classList.remove("show"),3500)}
function loading(btn,on,label){btn.dataset.label??=btn.childNodes[0].textContent;btn.disabled=on;btn.childNodes[0].textContent=on?label:btn.dataset.label}
function fill(card){[...$("#taskForm").elements].forEach(e=>{if(e.name&&Object.hasOwn(card,e.name))e.value=card[e.name]||""});scoreUI(formCard())}
function steps(n){$$('.steps span').forEach((s,i)=>s.classList.toggle('on',i<=n))}

async function analyze(){const text=$("#draft").value.trim(),err=$("#draftError"),btn=$("#analyzeBtn");err.textContent="";if(text.length<12){err.textContent="Добавьте хотя бы одно предложение о задаче.";return}loading(btn,true,"Анализируем… ");try{const d=await api('/analyze',{method:'POST',body:JSON.stringify({description:text})});state.card=d.card;$("#questions").innerHTML=d.questions.map((q,i)=>`<div class="question"><b>${i+1}</b><label>${esc(q.text)}<input data-field="${q.field}" placeholder="${esc(q.placeholder)}"></label></div>`).join('');fill(d.card);$("#questionsPanel").hidden=false;steps(1);$("#questionsPanel").scrollIntoView({behavior:'smooth'})}catch(e){err.textContent=e.message}finally{loading(btn,false)}}
function buildCard(){const card={...state.card};$$('[data-field]').forEach(i=>{if(i.value.trim())card[i.dataset.field]=i.value.trim()});fill(card);$("#cardPanel").hidden=false;steps(2);$("#cardPanel").scrollIntoView({behavior:'smooth'})}
function resetBuilder(){$("#draft").value="";$("#counter").textContent="0 / 1200";$("#questionsPanel").hidden=true;$("#cardPanel").hidden=true;$("#taskForm").reset();steps(0);scoreUI({})}
async function publish(e){e.preventDefault();if(!ensureRole("business"))return;const card=formCard(),err=$("#publishError"),btn=e.submitter;err.textContent="";if(!card.title.trim()||!card.context.trim()||!card.need.trim()){err.textContent="Нужны название, контекст и потребность.";return}if(card.deadline&&card.deadline<localDateString()){err.textContent="Дата окончания приёма откликов не может быть в прошлом.";return}if(!$("#confirm").checked){err.textContent="Подтвердите достоверность данных.";return}loading(btn,true,"Публикуем… ");try{const task=await api('/tasks',{method:'POST',body:JSON.stringify({...card,confirmed:true,owner_id:state.user.id,owner_name:displayName()})});state.tasks.unshift(task);counts();resetBuilder();go('catalog');toast('Задача опубликована',`Рейтинг ${task.score}/100. Студенты и команды уже могут откликнуться.`)}catch(x){err.textContent=x.message}finally{loading(btn,false)}}

function dateLocale(){return document.documentElement.lang==="en"?"en-US":document.documentElement.lang==="kk"?"kk-KZ":"ru-RU"}
function date(s){return s?new Intl.DateTimeFormat(dateLocale(),{day:"numeric",month:"short"}).format(new Date(s)):""}
function dateOnly(s){return s?new Intl.DateTimeFormat(dateLocale(),{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${s}T12:00:00`)):""}
function localDateString(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
const stageNames={open:"Открыта",in_progress:"В работе",completed:"Завершена"};
function currentUserApplicantPayload(){if(!state.user)return null;return {team_id:state.user.id,team_name:participantName(state.user),applicant_id:state.user.id,applicant_name:participantName(state.user),participant_type:state.user.participant_type==='team'?'team':'student'};}
function stageLabel(stage){return stageNames[stage]||stageNames.open}
function canPropose(task){return (task.stage||"open")==="open"&&(!task.deadline||task.deadline>=localDateString())}
function renderCatalog(){let q=$("#search").value.trim().toLowerCase(),ind=$("#industry").value,lvl=$("#readiness").value,sort=$("#sort").value;let tasks=state.tasks.filter(t=>(!q||`${t.title} ${t.context} ${t.need}`.toLowerCase().includes(q))&&(!ind||t.industry===ind)&&(!lvl||readiness(t.score).key===lvl));tasks.sort((a,b)=>sort==='newest'?new Date(b.created_at)-new Date(a.created_at):sort==='proposals'?b.proposals.length-a.proposals.length:b.score-a.score);$("#resultCount").textContent=`${tasks.length} ${plural(tasks.length)}`;$("#empty").hidden=!!tasks.length;$("#cards").innerHTML=tasks.map(t=>{const l=readiness(t.score),stage=t.stage||"open",allowed=canPropose(t);return `<article class="card ${l.key}"><div class="card-state"><span class="tag">${esc(t.industry)}</span><span class="task-stage stage-${stage}">${stageLabel(stage)}</span><span class="status ${l.key}"><i></i>${l.name}</span></div>${!allowed?`<span class="deadline-state">Приём откликов закрыт</span>`:""}<h2>${esc(t.title)}</h2><p>${esc(t.need||t.context)}</p><div class="metrics"><span class="metric"><small>Отклики</small><b>${t.proposals.length}</b></span><span class="metric"><small>Приём до</small><b>${t.deadline?dateOnly(t.deadline):"Без срока"}</b></span><span class="card-score">${t.score}<small>/100</small></span></div><button class="open" data-open="${t.id}">Посмотреть задачу <b>→</b></button></article>`}).join('')}
function openTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;state.active=id;const details=[["Контекст",t.context],["Потребность",t.need],["Пользователи",t.users],["Данные",t.data],["Ожидаемый результат",t.expected_result],["Критерии успеха",t.success_criteria],["Ограничения",t.constraints],["Связь",t.contact]],stage=t.stage||"open",allowed=canPropose(t),updates=[...(t.updates||[])].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$("#dialogBody").innerHTML=`<div class="dialog-inner"><span class="tag">${esc(t.industry)}</span><h2>${esc(t.title)}</h2><div class="dialog-score">${t.score}/100</div><section class="workflow-box"><div class="workflow-summary"><div><small>Этап задачи</small><span class="task-stage stage-${stage}">${stageLabel(stage)}</span></div><div><small>Приём откликов до</small><strong>${t.deadline?dateOnly(t.deadline):"Без срока"}</strong></div><strong class="deadline-state">${allowed?"Приём откликов открыт":"Приём откликов закрыт"}</strong></div><form id="workflowForm" class="workflow-form"><label class="field">Изменить этап<select name="stage"><option value="open" ${stage==="open"?"selected":""}>Открыта</option><option value="in_progress" ${stage==="in_progress"?"selected":""}>В работе</option><option value="completed" ${stage==="completed"?"selected":""}>Завершена</option></select></label><button class="primary" type="submit">Обновить этап <b>→</b></button></form></section>${updates.length?`<section class="task-updates"><h3>История изменений</h3>${updates.map(u=>`<div class="update-item"><span>${stageLabel(u.from)} <b>→</b> ${stageLabel(u.to)}</span><small>${date(u.created_at)}</small></div>`).join("")}</section>`:""}<div class="details">${details.map(d=>`<div class="detail"><small>${d[0]}</small><p>${esc(d[1]||"Не указано")}</p></div>`).join("")}</div>${allowed?`<form class="proposal-form" id="proposalForm"><h3>Предложить решение</h3><p>Опишите подход. Решение бизнес примет вручную.</p><div class="form-grid"><label class="field">Команда<select name="team_id">${state.teams.map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.skills.slice(0,2).join(", "))}</option>`).join("")}</select></label><label class="field">Срок<input name="timeline" placeholder="Например, 3 недели"></label><label class="field wide">Идея решения<textarea name="idea" rows="3"></textarea></label><label class="field wide">План работы<textarea name="plan" rows="3"></textarea></label><label class="field wide">Ссылка на прототип<input name="prototype" type="url" placeholder="https://..."></label></div><p class="error"></p><button class="primary" type="submit">Отправить отклик →</button></form>`:`<div class="proposal-closed"><b>Приём откликов закрыт</b></div>`}</div>`;$("#workflowForm").addEventListener("submit",changeTaskStage);if(allowed)$("#proposalForm").addEventListener("submit",submitProposal);$("#taskDialog").showModal()}
async function submitProposal(e){e.preventDefault();if(!ensureRole('student'))return;const data=Object.fromEntries(new FormData(e.currentTarget).entries()),err=e.currentTarget.querySelector('.error'),btn=e.submitter;err.textContent="";const task=state.tasks.find(t=>t.id===state.active);if(task&&!canPropose(task)){err.textContent=task.stage!="open"?"Приём откликов закрыт":"Срок приёма откликов истёк";return}if(!data.idea.trim()||!data.plan.trim()||!data.timeline.trim()){err.textContent="Заполните идею, план и срок.";return}loading(btn,true,"Отправляем… ");try{const applicantName=participantName(state.user),payload={...data,team_id:state.user.id,team_name:applicantName,applicant_id:state.user.id,applicant_name:applicantName,participant_type:state.user.participant_type==='team'?'team':'student'};const p=await api(`/tasks/${state.active}/proposals`,{method:'POST',body:JSON.stringify(payload)});state.tasks.find(t=>t.id===state.active).proposals.push(p);counts();$("#taskDialog").close();renderCatalog();toast('Отклик отправлен','Он появился в кабинете бизнеса.')}catch(x){err.textContent=x.message}finally{loading(btn,false)}}
function renderDecisions(){if(!isBusiness()){ $("#decisionList").innerHTML=`<div class="empty"><h2>Отклики недоступны</h2><p>Раздел виден только бизнесу.</p></div>`; return;} const tasks=state.tasks.filter(t=>t.owner_id===state.user.id&&t.proposals.length);$("#decisionList").innerHTML=tasks.length?tasks.map(t=>`<article class="decision"><header><div><p>${esc(t.industry)} · ${t.proposals.length} откл.</p><h2>${esc(t.title)}</h2></div><b>${t.score}/100</b></header>${t.proposals.map(p=>`<div class="proposal"><div class="team"><span class="avatar">${esc(p.team_name.split(/\s+/).map(w=>w[0]).join('').slice(0,2))}</span>${esc(p.team_name)}</div><p><b>${esc(p.idea)}</b>${esc(p.plan)} · ${esc(p.timeline)}</p><div class="decision-buttons"><button class="accept ${p.status==='selected'?'selected':''}" data-choice="selected" data-proposal="${p.id}" ${p.status!=='pending'?'disabled':''}>${p.status==='selected'?'Выбрана':'Выбрать'}</button><button class="reject ${p.status==='rejected'?'selected':''}" data-choice="rejected" data-proposal="${p.id}" ${p.status!=='pending'?'disabled':''}>${p.status==='rejected'?'Отклонена':'Отклонить'}</button></div></div>`).join('')}</article>`).join(''):`<div class="empty"><h2>Откликов пока нет</h2><p>Когда команда предложит решение, оно появится здесь.</p></div>`}
async function decide(id,choice){if(!isBusiness()){toast('Недоступно','Решения по откликам доступны только бизнесу.');return}try{const up=await api(`/proposals/${id}/decision`,{method:'POST',body:JSON.stringify({decision:choice})});state.tasks.forEach(t=>{const p=t.proposals.find(x=>x.id===id);if(p)Object.assign(p,up)});counts();renderDecisions();toast(choice==='selected'?'Команда выбрана':'Отклик отклонён','Решение бизнеса сохранено.')}catch(e){toast('Ошибка',e.message)}}

async function changeTaskStage(e){e.preventDefault();const task=state.tasks.find(t=>t.id===state.active),stage=new FormData(e.currentTarget).get("stage");if(!task)return;const previous=task.stage||"open";if(previous===stage)return;try{const updated=await api(`/tasks/${task.id}/stage`,{method:"POST",body:JSON.stringify({stage})});Object.assign(task,updated);state.knownUpdates=new Set(state.tasks.flatMap(t=>(t.updates||[]).map(update=>update.id)));counts();renderCatalog();renderDecisions();renderUpdates();const id=task.id;$("#taskDialog").close();openTask(id);toast("Этап задачи обновлён",`${stageLabel(previous)} → ${stageLabel(stage)}`)}catch(error){toast("Ошибка",error.message)}}
function renderUpdates(){const updates=state.tasks.flatMap(task=>(task.updates||[]).map(update=>({...update,taskId:task.id,taskTitle:task.title}))).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$("#updatesList").innerHTML=updates.length?updates.map(update=>`<article class="update-card"><div class="update-heading"><b>Этап задачи обновлён</b><time>${date(update.created_at)}</time></div><h2>${esc(update.taskTitle)}</h2><p>${stageLabel(update.from)} <b>→</b> ${stageLabel(update.to)}</p><button class="open update-open" data-open="${update.taskId}">Открыть задачу <b>→</b></button></article>`).join(""):`<div class="empty"><h2>Нет обновлений</h2><p>Обновления пока не появились.</p></div>`}
let refreshPending=false;
async function pollTaskUpdates(){
 if(refreshPending)return;
 refreshPending=true;
 try{
  const data=await api("/bootstrap"),all=data.tasks.flatMap(task=>(task.updates||[]).map(update=>({...update,taskTitle:task.title}))),fresh=all.filter(update=>!state.knownUpdates.has(update.id));
  state.knownUpdates=new Set(all.map(update=>update.id));
  state.tasks=data.tasks;state.teams=data.teams;
  counts();renderCatalog();renderDecisions();renderUpdates();
  if(fresh.length){const latest=fresh.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0];toast("Этап задачи обновлён",`${latest.taskTitle}: ${stageLabel(latest.to)}`)}
 }catch(_){}finally{refreshPending=false}
}
function showStudentCatalog(){
 $("#search").value="";$("#industry").value="";$("#readiness").value="";$("#sort").value="newest";
 go("catalog");
 pollTaskUpdates();
}
function counts(){$("#taskCount").textContent=state.tasks.length;$("#proposalCount").textContent=state.tasks.flatMap(t=>t.proposals).filter(p=>p.status==='pending').length;$("#updateCount").textContent=state.tasks.reduce((total,t)=>total+(t.updates||[]).length,0);const cur=$("#industry").value,inds=[...new Set(state.tasks.map(t=>t.industry))].sort();$("#industry").innerHTML='<option value="">Все темы</option>'+inds.map(x=>`<option>${esc(x)}</option>`).join('');$("#industry").value=cur}
async function load(){try{const d=await api('/bootstrap');state.tasks=d.tasks;state.teams=d.teams;state.knownUpdates=new Set(state.tasks.flatMap(t=>(t.updates||[]).map(update=>update.id)));counts();renderCatalog();renderDecisions();renderUpdates();if(!state.user){openAuth();}}catch(e){toast('Сервер недоступен','Запустите проект командой python app.py.')}}

state.user=loadSession();updateAuthUI();
$$('.nav').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$$('[data-new]').forEach(b=>b.addEventListener('click',()=>go('builder')));$("#authButton").addEventListener('click',()=>openAuth());$("#logoutButton").addEventListener('click',logout);$("#authClose").addEventListener('click',()=>$("#authDialog").close());$("#authForm").addEventListener('submit',requestCode);$("#codeForm").addEventListener('submit',verifyCode);$$("#authForm [name=role]").forEach(input=>input.addEventListener('change',syncAuthFields));$("#authForm [name=participant_type]").addEventListener('change',syncAuthFields);$("#authBack").addEventListener('click',()=>{$('#authForm').hidden=false;$('#codeForm').hidden=true;$('#codeError').textContent='';$('#authError').textContent='';});$("#draft").addEventListener('input',e=>$("#counter").textContent=`${e.target.value.length} / 1200`);$("#exampleBtn").addEventListener('click',()=>{$("#draft").value='Хотим сократить очереди в столовой университета с помощью цифрового сервиса.';$("#draft").dispatchEvent(new Event('input'))});$("#analyzeBtn").addEventListener('click',analyze);$("#buildBtn").addEventListener('click',buildCard);$("#taskForm").addEventListener('input',()=>scoreUI(formCard()));$("#taskForm").addEventListener('submit',publish);['#search','#industry','#readiness','#sort'].forEach(s=>$(s).addEventListener('input',renderCatalog));$("#cards").addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openTask(b.dataset.open)});$("#decisionList").addEventListener('click',e=>{const b=e.target.closest('[data-choice]');if(b)decide(b.dataset.proposal,b.dataset.choice)});$("#updatesList").addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openTask(b.dataset.open)});$(".close").addEventListener('click',()=>$("#taskDialog").close());$("#taskDialog").addEventListener('click',e=>{if(e.target===$("#taskDialog"))e.target.close()});$("#taskDeadline").min=localDateString();scoreUI({});load();setInterval(pollTaskUpdates,15000);go(['builder','catalog','decisions','updates','about'].includes(location.hash.slice(1))?location.hash.slice(1):(isBusiness()?'builder':'catalog'));if(isStudent())showStudentCatalog();
