"use strict";
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),esc=(s="")=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const state={tasks:[],teams:[],card:{},active:null};
const rules=[
 {label:"Контекст и потребность",points:20,fields:["context","need"]},{label:"Данные и материалы",points:20,fields:["data"]},
 {label:"Ожидаемый результат",points:15,fields:["expected_result"]},{label:"Критерии успеха",points:15,fields:["success_criteria"]},
 {label:"Ограничения",points:10,fields:["constraints"]},{label:"Пользователи",points:10,fields:["users"]},{label:"Связь с бизнесом",points:10,fields:["contact"]}
];
const localStorageKey="taskforge.demo.v1";
const localTeams=[
 {id:"team-1",name:"Data Nomads",interests:["ритейл","аналитика"],skills:["Python","ML","FastAPI"]},
 {id:"team-2",name:"Qadam Lab",interests:["образование","доступность"],skills:["UX","JavaScript","NLP"]},
 {id:"team-3",name:"Green Pulse",interests:["экология","города"],skills:["IoT","DataViz","Python"]},
 {id:"team-4",name:"Finity",interests:["финтех","безопасность"],skills:["React","Risk","API"]},
 {id:"team-5",name:"Steppe Vision",interests:["CV","логистика"],skills:["Computer Vision","Python","Mobile"]}
];
const localQuestions={
 need:["Что именно должно измениться после решения задачи?","Сформулируйте желаемое изменение"],users:["Кто будет пользоваться результатом?","Роли или группы пользователей"],
 data:["Какие данные, материалы или примеры вы предоставите?","Формат, объём и источник данных"],expected_result:["Какой конкретный результат должна передать команда?","Прототип, модель, исследование или сервис"],
 success_criteria:["По каким измеримым признакам вы примете решение?","Метрики или проверяемые условия"],constraints:["Какие есть сроки, технологии или ограничения?","Срок, стек, запреты"],
 contact:["Как команда сможет общаться с бизнесом?","Контакт и формат консультаций"]
};
const clone=value=>typeof structuredClone==="function"?structuredClone(value):JSON.parse(JSON.stringify(value));
const localId=prefix=>`${prefix}-${typeof crypto!=="undefined"&&crypto.randomUUID?crypto.randomUUID().slice(0,8):Math.random().toString(16).slice(2,10)}`;
function enrichLocal(task){let score=0;const breakdown=[],missing=[];for(const rule of rules){const earned=task.confirmed&&rule.fields.every(field=>String(task[field]||"").trim().length>=3)?rule.points:0;score+=earned;breakdown.push({label:rule.label,earned,max:rule.points});if(!earned)missing.push(rule.label)}return Object.assign(task,{score,breakdown,missing,readiness:score>=90?"priority":score>=70?"ready":score>=40?"workable":"draft"})}
function seedTask(data){return enrichLocal(Object.assign({users:"",data:"",constraints:"",expected_result:"",success_criteria:"",contact:"",confirmed:true,published:true,proposals:[]},data))}
function seedLocalDb(){
 const tasks=[
  seedTask({id:"task-1",title:"Сократить очереди в университетской столовой",industry:"Образование",context:"В обед студенты ждут заказ до 25 минут, сотрудники не видят будущую нагрузку.",need:"Нужен сервис предзаказа и прогнозирования нагрузки по времени.",created_at:"2026-09-22T09:00:00+00:00",users:"Студенты, преподаватели и сотрудники столовой.",data:"История продаж за 6 месяцев, меню и расписание пар.",constraints:"MVP без онлайн-оплаты; запуск за 4 недели.",expected_result:"Веб-MVP предзаказа и панель прогноза нагрузки.",success_criteria:"Среднее ожидание ниже 10 минут; 60% заказов вовремя.",contact:"Менеджер столовой; консультация по средам."}),
  seedTask({id:"task-2",title:"Прогнозировать остатки скоропортящихся товаров",industry:"Ритейл",context:"Магазины списывают свежие продукты из-за неточного ручного заказа.",need:"Нужен прогноз спроса на 7 дней по товарным категориям.",created_at:"2026-09-21T13:30:00+00:00",users:"Управляющие магазинов и специалисты по закупкам.",data:"Продажи, остатки, промо и списания по 12 магазинам за год.",constraints:"Без персональных данных; запуск на обычном ноутбуке.",expected_result:"Модель прогноза и рекомендации объёма заказа.",success_criteria:"Ошибка ниже baseline минимум на 15%.",contact:"Продуктовый аналитик; две консультации в неделю."}),
  seedTask({id:"task-3",title:"Карта переполненных контейнерных площадок",industry:"Экология",context:"Жители сообщают о переполнении по разным каналам, заявки дублируются.",need:"Нужно собирать сигналы на карте и расставлять приоритеты.",created_at:"2026-09-20T08:15:00+00:00",users:"Жители и диспетчеры службы вывоза.",data:"Примеры обращений и координаты 80 площадок.",expected_result:"Прототип карты с фильтром по срочности.",success_criteria:"Критичные точки находятся меньше чем за 2 минуты.",contact:"Координатор проекта, созвон раз в неделю."}),
  seedTask({id:"task-4",title:"Объяснять причины отклонения заявок на микрокредит",industry:"Финтех",context:"Клиенты получают формальный отказ и повторяют заявку без изменений.",need:"Нужно понятное объяснение без раскрытия закрытых правил скоринга.",created_at:"2026-09-19T15:45:00+00:00",users:"Клиенты приложения и специалисты поддержки.",expected_result:"Прототип экрана и библиотека безопасных формулировок.",constraints:"Без чувствительных признаков и раскрытия весов скоринга."}),
  seedTask({id:"task-5",title:"Навигация по доступным маршрутам внутри кампуса",industry:"Городская среда",context:"Гостям сложно понять, какой вход доступен маломобильному человеку.",need:"Нужна карта доступных входов и маршрутов.",created_at:"2026-09-18T11:20:00+00:00",users:"Маломобильные посетители и сопровождающие."})
 ];
 tasks[0].proposals.push({id:"proposal-1",team_id:"team-2",team_name:"Qadam Lab",idea:"PWA-предзаказ с временными слотами",plan:"Прототип, тест на одной точке, анализ очереди",timeline:"3 недели",prototype:"https://example.com/demo",status:"pending",created_at:new Date().toISOString()});
 tasks[1].proposals.push({id:"proposal-2",team_id:"team-1",team_name:"Data Nomads",idea:"Иерархический прогноз по магазинам",plan:"Очистка, backtest, API прогноза",timeline:"4 недели",prototype:"https://example.com/demo",status:"pending",created_at:new Date().toISOString()});
 return {tasks,teams:clone(localTeams)};
}
let localDbCache;
function loadLocalDb(){if(localDbCache)return localDbCache;try{const saved=JSON.parse(localStorage.getItem(localStorageKey));if(saved&&Array.isArray(saved.tasks)&&Array.isArray(saved.teams))return localDbCache=saved}catch(_){}return localDbCache=seedLocalDb()}
function saveLocalDb(db){localDbCache=db;try{localStorage.setItem(localStorageKey,JSON.stringify(db))}catch(_){}}
function analyzeLocal(text){const clean=text.replace(/\s+/g," ").trim(),low=clean.toLowerCase(),words=clean.split(" ");let industry="Другое";const industries={"Образование":["университет","школ","студент","обуч"],"Ритейл":["магазин","товар","продаж"],"Финтех":["банк","кредит","финанс"],"Экология":["отход","мусор","эколог"],"Городская среда":["город","маршрут","транспорт","кампус"]};for(const [name,marks] of Object.entries(industries))if(marks.some(mark=>low.includes(mark))){industry=name;break}const title=words.slice(0,9).join(" ").replace(/[.,;:!?]+$/g,"")+(words.length>9?"…":""),card={title:title.slice(0,100),industry,context:clean,need:"",users:"",data:"",constraints:"",expected_result:"",success_criteria:"",contact:""};const markers={users:["для ","пользовател","клиент","сотрудник","студент"],data:["данн","csv","таблиц","api"],constraints:["срок","нельзя","огранич","недел"],expected_result:["прототип","сервис","модель","приложение"],success_criteria:["процент","%","метрик","сниз"],contact:["контакт","созвон","консультац"]};const order=["need","users","data","expected_result","success_criteria","constraints","contact"],found=new Set(Object.entries(markers).filter(([,marks])=>marks.some(mark=>low.includes(mark))).map(([field])=>field)),missing=order.filter(field=>!found.has(field));if(missing.length<3)missing.push(...order.filter(field=>!missing.includes(field)));return {card,questions:missing.slice(0,5).map(field=>({field,text:localQuestions[field][0],placeholder:localQuestions[field][1]})),analysis:{mode:"browser-local",invented_facts:false}}}
function localApi(path,options={}){const db=loadLocalDb();let input={};if(options.body)try{input=JSON.parse(options.body)}catch(_){throw Error("Некорректный JSON")}if(path==="/bootstrap")return clone({tasks:[...db.tasks].sort((a,b)=>b.score-a.score),teams:db.teams});if(path==="/tasks"&&(!options.method||options.method==="GET"))return clone(db.tasks);if(path==="/analyze"){const text=String(input.description||"").trim();if(text.length<12)throw Error("Описание должно содержать хотя бы 12 символов");return analyzeLocal(text.slice(0,1200))}if(path==="/tasks"&&options.method==="POST"){if(!["title","context","need"].every(field=>String(input[field]||"").trim()))throw Error("Нужны название, контекст и потребность");if(input.confirmed!==true)throw Error("Подтвердите карточку");const fields=["title","industry","context","need","users","data","constraints","expected_result","success_criteria","contact"],task=Object.fromEntries(fields.map(field=>[field,String(input[field]||"").trim().slice(0,2000)]));Object.assign(task,{id:localId("task"),title:task.title.slice(0,100),industry:task.industry||"Другое",confirmed:true,published:true,created_at:new Date().toISOString(),proposals:[]});enrichLocal(task);db.tasks.push(task);saveLocalDb(db);return clone(task)}let match=path.match(/^\/tasks\/([^/]+)\/proposals$/);if(match){const task=db.tasks.find(item=>item.id===match[1]),team=db.teams.find(item=>item.id===input.team_id);if(!task||!team)throw Error("Задача или команда не найдена");if(!["idea","plan","timeline"].every(field=>String(input[field]||"").trim()))throw Error("Заполните идею, план и срок");const proposal={id:localId("proposal"),team_id:team.id,team_name:team.name,idea:String(input.idea).slice(0,500),plan:String(input.plan).slice(0,1000),timeline:String(input.timeline).slice(0,100),prototype:String(input.prototype||"").slice(0,500),status:"pending",created_at:new Date().toISOString()};task.proposals.push(proposal);saveLocalDb(db);return clone(proposal)}match=path.match(/^\/proposals\/([^/]+)\/decision$/);if(match){if(!["selected","rejected"].includes(input.decision))throw Error("Можно выбрать или отклонить");for(const task of db.tasks){const proposal=task.proposals.find(item=>item.id===match[1]);if(proposal){proposal.status=input.decision;proposal.decided_at=new Date().toISOString();saveLocalDb(db);return clone(proposal)}}throw Error("Отклик не найден")}throw Error("Маршрут не найден")}
let apiMode="remote";
async function api(path,options={}){if(apiMode==="local")return localApi(path,options);let response;try{response=await fetch("/api"+path,{headers:{"Content-Type":"application/json"},...options})}catch(_){apiMode="local";return localApi(path,options)}const type=response.headers.get("Content-Type")||"";if(!type.includes("application/json")){if(response.ok||[404,405,501].includes(response.status)){apiMode="local";return localApi(path,options)}throw Error(`Ошибка запроса (HTTP ${response.status})`)}const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||`Ошибка запроса (HTTP ${response.status})`);return data}
function readiness(score){return score>=90?{key:"priority",name:"Приоритетная"}:score>=70?{key:"ready",name:"Готовая"}:score>=40?{key:"workable",name:"Рабочая"}:{key:"draft",name:"Черновик"}}
function plural(n){return n%10===1&&n%100!==11?"задача":n%10>1&&n%10<5&&(n%100<10||n%100>=20)?"задачи":"задач"}
function formCard(){return Object.fromEntries(new FormData($("#taskForm")).entries())}
function rating(card){let score=0;const rows=rules.map(r=>{const yes=r.fields.every(f=>(card[f]||"").trim().length>=3);if(yes)score+=r.points;return{...r,yes}});return{score,rows}}
function scoreUI(card={}){const {score,rows}=rating(card),level=readiness(score);$("#ring").style.setProperty("--value",score);$("#score").textContent=score;$("#level").textContent=level.name;$("#filled").textContent=`${rows.filter(r=>r.yes).length} из 7`;$(".level>i").style.background={draft:"var(--orange)",workable:"var(--purple)",ready:"var(--pink-soft)",priority:"var(--pink)"}[level.key];$("#breakdown").innerHTML=rows.map(r=>`<div class="break ${r.yes?"yes":""}"><span>${r.label}</span><b>${r.yes?"+"+r.points:"0"}/${r.points}</b><span class="track"><i></i></span></div>`).join("");const next=rows.find(r=>!r.yes);$("#tip").innerHTML=next?`<b>Можно добавить +${next.points}</b>Заполните: ${next.label.toLowerCase()}.`:`<b>Карточка заполнена</b>Все критерии рейтинга подтверждены.`}
function go(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===name));history.replaceState(null,'','#'+name);if(name==='catalog')renderCatalog();if(name==='decisions')renderDecisions();scrollTo({top:0,behavior:'smooth'})}
function toast(title,text){$("#toastTitle").textContent=title;$("#toastText").textContent=text;$("#toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("#toast").classList.remove("show"),3500)}
function loading(btn,on,label){btn.dataset.label??=btn.childNodes[0].textContent;btn.disabled=on;btn.childNodes[0].textContent=on?label:btn.dataset.label}
function fill(card){[...$("#taskForm").elements].forEach(e=>{if(e.name&&Object.hasOwn(card,e.name))e.value=card[e.name]||""});scoreUI(formCard())}
function steps(n){$$('.steps span').forEach((s,i)=>s.classList.toggle('on',i<=n))}

async function analyze(){const text=$("#draft").value.trim(),err=$("#draftError"),btn=$("#analyzeBtn");err.textContent="";if(text.length<12){err.textContent="Добавьте хотя бы одно предложение о задаче.";return}loading(btn,true,"Анализируем… ");try{const d=await api('/analyze',{method:'POST',body:JSON.stringify({description:text})});state.card=d.card;$("#questions").innerHTML=d.questions.map((q,i)=>`<div class="question"><b>${i+1}</b><label>${esc(q.text)}<input data-field="${q.field}" placeholder="${esc(q.placeholder)}"></label></div>`).join('');fill(d.card);$("#questionsPanel").hidden=false;steps(1);$("#questionsPanel").scrollIntoView({behavior:'smooth'})}catch(e){err.textContent=e.message}finally{loading(btn,false)}}
function buildCard(){const card={...state.card};$$('[data-field]').forEach(i=>{if(i.value.trim())card[i.dataset.field]=i.value.trim()});fill(card);$("#cardPanel").hidden=false;steps(2);$("#cardPanel").scrollIntoView({behavior:'smooth'})}
function resetBuilder(){$("#draft").value="";$("#counter").textContent="0 / 1200";$("#questionsPanel").hidden=true;$("#cardPanel").hidden=true;$("#taskForm").reset();steps(0);scoreUI({})}
async function publish(e){e.preventDefault();const card=formCard(),err=$("#publishError"),btn=e.submitter;err.textContent="";if(!card.title.trim()||!card.context.trim()||!card.need.trim()){err.textContent="Нужны название, контекст и потребность.";return}if(!$("#confirm").checked){err.textContent="Подтвердите достоверность данных.";return}loading(btn,true,"Публикуем… ");try{const task=await api('/tasks',{method:'POST',body:JSON.stringify({...card,confirmed:true})});state.tasks.unshift(task);counts();resetBuilder();go('catalog');toast('Задача опубликована',`Рейтинг ${task.score}/100. Команды уже могут откликнуться.`)}catch(x){err.textContent=x.message}finally{loading(btn,false)}}

function date(s){return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(s))}
function renderCatalog(){let q=$("#search").value.trim().toLowerCase(),ind=$("#industry").value,lvl=$("#readiness").value,sort=$("#sort").value;let tasks=state.tasks.filter(t=>(!q||`${t.title} ${t.context} ${t.need}`.toLowerCase().includes(q))&&(!ind||t.industry===ind)&&(!lvl||readiness(t.score).key===lvl));tasks.sort((a,b)=>sort==='newest'?new Date(b.created_at)-new Date(a.created_at):sort==='proposals'?b.proposals.length-a.proposals.length:b.score-a.score);$("#resultCount").textContent=`${tasks.length} ${plural(tasks.length)}`;$("#empty").hidden=!!tasks.length;$("#cards").innerHTML=tasks.map(t=>{const l=readiness(t.score);return `<article class="card ${l.key}"><div class="card-top"><span class="tag">${esc(t.industry)}</span><span class="status ${l.key}"><i></i>${l.name}</span></div><h2>${esc(t.title)}</h2><p>${esc(t.need||t.context)}</p><div class="metrics"><span class="metric"><small>Отклики</small><b>${t.proposals.length}</b></span><span class="metric"><small>Создана</small><b>${date(t.created_at)}</b></span><span class="card-score">${t.score}<small>/100</small></span></div><button class="open" data-open="${t.id}">Посмотреть задачу <b>→</b></button></article>`}).join('')}
function openTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;state.active=id;const details=[["Контекст",t.context],["Потребность",t.need],["Пользователи",t.users],["Данные",t.data],["Ожидаемый результат",t.expected_result],["Критерии успеха",t.success_criteria],["Ограничения",t.constraints],["Связь",t.contact]];$("#dialogBody").innerHTML=`<div class="dialog-inner"><span class="tag">${esc(t.industry)}</span><h2>${esc(t.title)}</h2><div class="dialog-score">${t.score}/100</div><div class="details">${details.map(d=>`<div class="detail"><small>${d[0]}</small><p>${esc(d[1]||'Не указано')}</p></div>`).join('')}</div><form class="proposal-form" id="proposalForm"><h3>Предложить решение</h3><p>Опишите подход. Решение бизнес примет вручную.</p><div class="form-grid"><label class="field">Команда<select name="team_id">${state.teams.map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.skills.slice(0,2).join(', '))}</option>`).join('')}</select></label><label class="field">Срок<input name="timeline" placeholder="Например, 3 недели"></label><label class="field wide">Идея решения<textarea name="idea" rows="3"></textarea></label><label class="field wide">План работы<textarea name="plan" rows="3"></textarea></label><label class="field wide">Ссылка на прототип<input name="prototype" type="url" placeholder="https://..."></label></div><p class="error"></p><button class="primary" type="submit">Отправить отклик →</button></form></div>`;$("#proposalForm").addEventListener('submit',submitProposal);$("#taskDialog").showModal()}
async function submitProposal(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries()),err=e.currentTarget.querySelector('.error'),btn=e.submitter;err.textContent="";if(!data.idea.trim()||!data.plan.trim()||!data.timeline.trim()){err.textContent="Заполните идею, план и срок.";return}loading(btn,true,"Отправляем… ");try{const p=await api(`/tasks/${state.active}/proposals`,{method:'POST',body:JSON.stringify(data)});state.tasks.find(t=>t.id===state.active).proposals.push(p);counts();$("#taskDialog").close();renderCatalog();toast('Отклик отправлен','Он появился в кабинете бизнеса.')}catch(x){err.textContent=x.message}finally{loading(btn,false)}}
function renderDecisions(){const tasks=state.tasks.filter(t=>t.proposals.length);$("#decisionList").innerHTML=tasks.length?tasks.map(t=>`<article class="decision"><header><div><p>${esc(t.industry)} · ${t.proposals.length} откл.</p><h2>${esc(t.title)}</h2></div><b>${t.score}/100</b></header>${t.proposals.map(p=>`<div class="proposal"><div class="team"><span class="avatar">${esc(p.team_name.split(/\s+/).map(w=>w[0]).join('').slice(0,2))}</span>${esc(p.team_name)}</div><p><b>${esc(p.idea)}</b>${esc(p.plan)} · ${esc(p.timeline)}</p><div class="decision-buttons"><button class="accept ${p.status==='selected'?'selected':''}" data-choice="selected" data-proposal="${p.id}" ${p.status!=='pending'?'disabled':''}>${p.status==='selected'?'Выбрана':'Выбрать'}</button><button class="reject ${p.status==='rejected'?'selected':''}" data-choice="rejected" data-proposal="${p.id}" ${p.status!=='pending'?'disabled':''}>${p.status==='rejected'?'Отклонена':'Отклонить'}</button></div></div>`).join('')}</article>`).join(''):`<div class="empty"><h2>Откликов пока нет</h2><p>Когда команда предложит решение, оно появится здесь.</p></div>`}
async function decide(id,choice){try{const up=await api(`/proposals/${id}/decision`,{method:'POST',body:JSON.stringify({decision:choice})});state.tasks.forEach(t=>{const p=t.proposals.find(x=>x.id===id);if(p)Object.assign(p,up)});counts();renderDecisions();toast(choice==='selected'?'Команда выбрана':'Отклик отклонён','Решение бизнеса сохранено.')}catch(e){toast('Ошибка',e.message)}}
function counts(){$("#taskCount").textContent=state.tasks.length;$("#proposalCount").textContent=state.tasks.flatMap(t=>t.proposals).filter(p=>p.status==='pending').length;const cur=$("#industry").value,inds=[...new Set(state.tasks.map(t=>t.industry))].sort();$("#industry").innerHTML='<option value="">Все темы</option>'+inds.map(x=>`<option>${esc(x)}</option>`).join('');$("#industry").value=cur}
async function load(){try{const d=await api('/bootstrap');state.tasks=d.tasks;state.teams=d.teams;counts();renderCatalog();renderDecisions()}catch(e){toast('Сервер недоступен','Запустите проект командой python app.py.')}}

$$('.nav').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$$('[data-new]').forEach(b=>b.addEventListener('click',()=>go('builder')));$("#draft").addEventListener('input',e=>$("#counter").textContent=`${e.target.value.length} / 1200`);$("#exampleBtn").addEventListener('click',()=>{$("#draft").value='Хотим сократить очереди в столовой университета с помощью цифрового сервиса.';$("#draft").dispatchEvent(new Event('input'))});$("#analyzeBtn").addEventListener('click',analyze);$("#buildBtn").addEventListener('click',buildCard);$("#taskForm").addEventListener('input',()=>scoreUI(formCard()));$("#taskForm").addEventListener('submit',publish);['#search','#industry','#readiness','#sort'].forEach(s=>$(s).addEventListener('input',renderCatalog));$("#cards").addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openTask(b.dataset.open)});$("#decisionList").addEventListener('click',e=>{const b=e.target.closest('[data-choice]');if(b)decide(b.dataset.proposal,b.dataset.choice)});$(".close").addEventListener('click',()=>$("#taskDialog").close());$("#taskDialog").addEventListener('click',e=>{if(e.target===$("#taskDialog"))e.target.close()});scoreUI({});load();go(['builder','catalog','decisions','about'].includes(location.hash.slice(1))?location.hash.slice(1):'builder');
